# Merged on top of default API config response
# https://access.redhat.com/documentation/en-us/red_hat_quay/3/html/manage_red_hat_quay/quay-schema

BUILDLOGS_REDIS: { host: "{{ quay_redis_hostname }}", password: "{{ quay_redis_password }}", port: "{{ quay_redis_port }}" }
USER_EVENTS_REDIS: { host: "{{ quay_redis_hostname }}", password: "{{ quay_redis_password }}", port: "{{ quay_redis_port }}" }

FEATURE_ANONYMOUS_ACCESS: true
FEATURE_APP_REGISTRY: false
FEATURE_APP_SPECIFIC_TOKENS: true
FEATURE_CHANGE_TAG_EXPIRATION: true
FEATURE_DIRECT_LOGIN: true
FEATURE_INVITE_ONLY_USER_CREATION: false
FEATURE_PARTIAL_USER_AUTOCOMPLETE: true
FEATURE_PROXY_STORAGE: true
FEATURE_REPO_MIRROR: "{{ quay_repomirror_feature }}"
FEATURE_REQUIRE_TEAM_INVITE: false
FEATURE_RESTRICTED_V1_PUSH: true
FEATURE_SECURITY_NOTIFICATIONS: true
FEATURE_USERNAME_CONFIRMATION: true
FEATURE_USER_CREATION: true

REPO_MIRROR_TLS_VERIFY: true
REPO_MIRROR_SERVER_HOSTNAME: "{{ quay_hostname }}"

# PREFERRED_URL_SCHEME: https
PREFERRED_URL_SCHEME: http
REQUIRE_ENCRYPTED_BASIC_AUTH: true
FEATURE_SECURITY_SCANNER: true
SECURITY_SCANNER_ENDPOINT: "https://{{ clair_hostname }}:6060"
SERVER_HOSTNAME: "{{ quay_hostname }}"
SETUP_COMPLETE: true
SUPER_USERS: "{{ quay_superusers }}"
SECRET_KEY: "{{ quay_api_scanner_key_id }}"
EXTERNAL_TLS_TERMINATION: false
