inventory_name: dev
ansible_ssh_user: centos
ansible_become_pass: T$est089

drop_quay_db: true
delete_old_quay_config: true
remove_all_folders: true

remove_redis_container: true
remove_quay_container: true
remove_clair_container: true
remove_postgres_container: true
remove_quayconfig_container: true

quay_hostname: quay.dev
quay_runtime_user: root
quay_vm_user: root
quay_initial_superuser_username: yoda
quay_initial_superuser_email: yoda@quay.dev

postgres_ssl_mode: false
prefered_storage: default

is_quay: false
data_dir_base: /var/data
quay_data_dir: /var/data/quay
quay_repomirror_storage_dir: /var/data/repomirror
quay_setup_name: quayconfig
quay_repomirror_feature: false
quay_db_dbname: quay_db
quay_db_username: quay_user
quay_db_admin_username: postgres
quay_redis_port: 6379
quay_db_port: 5432
quay_db_admin_password: "{{ secrets.quay_db_admin_password }}"
quay_db_password: "{{ secrets.quay_db_password }}"
quay_registry_password: "{{ secrets.quay_registry_password }}"
quay_logo_file: "../../files/common/custom-logo.svg"

is_clair: false
clair_runtime_user: root
clair_hostname: clair.dev
clair_force_new_key: true
clair_db_username: clair_user
clair_db_admin_username: postgres
clair_db_dbname: clair_db
clair_db_port: 5432
clair_data_dir: /var/data/clair
clair_proxy_mode: false
# clair_proxy_name:
# clair_proxy_port:

image_registry: quay.io
image_registry_user: dpawlik

postgres_image: "rhscl/postgresql-96-rhel7"
redis_image: "rhscl/redis-32-rhel7:3.2"
quay_image: "{{ image_registry }}/projectquay/quay:v3.5.2"
clair_image: "{{ image_registry }}/projectquay/clair-jwt:v2.1.2-alpine"
test_image: "registry.access.redhat.com/ubi8/ubi-minimal:8.0"
test_image_local: "{{ quay_hostname }}/ubi8/ubi-minimal:8.0"
test_image_tag: "8.0"
test_image_api: "ubi8/ubi-minimal"
test_skip_login_pull: true

quay_test_robot_name: ubi8+test_robot
quay_test_robot_password: 2M8ILGF6GZST6RFSINNGCMZBZUHGKPDY6Y50MIB11E7KY783XKS6AMYKQSFOW2JS
quay_system_test_manifest: sha256:90e7a8c15504099bd3a6656ad5f75b26c25822fba6d09d3b067f24c4c6faf4ba
quay_system_test_bearer: zXhBoyJLD4ErnP4Slh0fQWTVETK0yqF1eRW6XyAD

quay_cert_file: "{{ certs.quay_cert_file }}"
quay_key_file: "{{ certs.quay_key_file }}"
quay_ca_file: "{{ certs.quay_ca_file }}"
quay_db_ca_file: "{{ certs.postgres_ssl_ca }}"

clair_cert_file: "{{ certs.clair_cert_file }}"
clair_key_file: "{{ certs.clair_key_file }}"
clair_ca_files: "{{ certs.clair_ca_files }}"
clair_db_ca_file: "{{ certs.postgres_ssl_ca }}"

postgres_ssl_crt: "{{ certs.postgres_ssl_crt }}"
postgres_ssl_key: "{{ certs.postgres_ssl_key }}"
postgres_ssl_ca: "{{ certs.postgres_ssl_ca }}"

# quay_s3_cert_file: ""
# quay_ldap_cert_file: ""
# quay_s3_cert_name: ""
# quay_ldap_cert_name: ""

secrets:
  quay_initial_superuser_password: mypassword
  quay_db_admin_password: postgres
  quay_setup_password: mypassword2
  quay_db_password: postgres
  quay_registry_password: myquay.io_password
  clair_db_admin_password: postgres
  clair_db_password: postgres
  quay_redis_password: mypassword7
  azure_account_key: mypassword8
  azure_sas_token: mypassword9
  ldap_password: mypassword10

certs:
  quay_cert_file: |
    -----BEGIN CERTIFICATE-----
    MIIDSjCCAjICFEritoVlMkRRgARbHgCp63+HRYn5MA0GCSqGSIb3DQEBCwUAMFgx
    CzAJBgNVBAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFX
    MSUwIwYDVQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcx
    OTEyMjcxM1oXDTMxMDcxNzEyMjcxM1owazELMAkGA1UEBhMCUEwxEDAOBgNVBAgM
    B1dST0NMQVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFy
    Y2hTb2Z0d2FyZUZhY3RvcnkxETAPBgNVBAMMCHF1YXkuZGV2MIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwESjAJqQ6cnwDyoKzTZ8benASm/Yg89BITis
    Nc6zOo2PY8Lq42UsVX/k3agIfedx0vCzgatto/dk8WwvWyt9nbPYzEC5Duy0vURg
    PUPMM3/65DRcOrlFuqumhRbb0FsKbuRNdlQtDXvGioC46fm3zeRlBR/fxI8AU7pu
    w9Le0Dr27blDfHi1/9ikprar0TjHWzbrv2ONTGEjL3noqSfmaybGItGG+6KXACwx
    2w7xiw/bEuD7iqlrwTqpe0hUkAIzhd/aiXcK8SKccCr8oAZJgAqSMLlsFn3zmYU4
    J4+l8ktPBvJ4JiavnMhUM6vhgqkotq9D1lUAtsxxAoXpZqE5xwIDAQABMA0GCSqG
    SIb3DQEBCwUAA4IBAQBxjosUCMSbtFawhEr61iVac9UmMwMAvY7tQ23ZA8QTBOhw
    Zh39cJ5phmYZkm+NWIefrNMTFI2CSVs9MKiacWOurbpX1qkfYdF4a5yoKhFdWyuC
    JAa0C3I3RdTXJrbpvoQoqHDmPES07KZiKigksZn2uB0zu/woQjdQS6oFoI7z4q81
    PBdKn7yh6EIVntbCLLCQO1eMGs49NStyvDnY8uQCqUXXKA8BTRYrGgumW8te0g1j
    P/e9Gs8YijnM2dBDugmFg+Ygg/H+z+0TqU+MCeCelHXhPXgjd683CSnnnN7dNFUc
    9WJ/F3dStgvCfwMVthwBo1ZTeaPrvCEhSvJ+MaAI
    -----END CERTIFICATE-----
  quay_key_file: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDARKMAmpDpyfAP
    KgrNNnxt6cBKb9iDz0EhOKw1zrM6jY9jwurjZSxVf+TdqAh953HS8LOBq22j92Tx
    bC9bK32ds9jMQLkO7LS9RGA9Q8wzf/rkNFw6uUW6q6aFFtvQWwpu5E12VC0Ne8aK
    gLjp+bfN5GUFH9/EjwBTum7D0t7QOvbtuUN8eLX/2KSmtqvROMdbNuu/Y41MYSMv
    eeipJ+ZrJsYi0Yb7opcALDHbDvGLD9sS4PuKqWvBOql7SFSQAjOF39qJdwrxIpxw
    KvygBkmACpIwuWwWffOZhTgnj6XyS08G8ngmJq+cyFQzq+GCqSi2r0PWVQC2zHEC
    helmoTnHAgMBAAECggEAOFJi5YRhuvqaxfZs35x8ar40xBlrdYE69P5jBAge3KIn
    RPQOVrqGeC1U39GfWzJ3V3GHRA7xuTx5Z3dnj+93hsDuWzcCfuq8L01eW9QGd3eg
    CUWFVvZ7BKnPx+DgV3Kz5bQfNPCHmhGOIXh/spqiS0ACj7O8mxnA4MYWOGsHNjvt
    onA9hg94Kp29jo1eyfIRR/E+Rs4SvOx2njLHkiTC0nKKwflqFj9ZiV1CWJWpg90N
    jv90RaxdIQ8uhsLj7/cQDAf+Dr2ZblEiTluh+tGrcMgTpSNaQoJi6bHiBlwT9VlK
    jQSPhb0kPGsbBweRTYEkeG7tA91aG5eGtp/Gu0mk4QKBgQDi2L8G/QIkKwMqhDyR
    BjRXgYFNB9TKVEh8jncshhnnbLeTeEzki1XL0x1CEcRnCo5hwsuUo4hPGXfMb+v7
    PKeZu9T9FqQRHaiaw/b5BXOSPkchNGCqxbBzcCeh44+6gtMiG7lw1yzJNhvz1UjI
    wS2xUQcB+F9cE5XIxV+vaSTC/wKBgQDY+kGhhIs1coFAr05SfOrzhHC0BnfHVGIa
    ys9K6a8sXoGVcVz560DtuucLBJPGJCRTQT3sLoPU3m3tQpnW37qA/6yWXVwbngzX
    Fp115ywkRoswlujU3b38maIhlWS51oDl0GDkZOqQvqNQ87ON0gLrvCCtXGvQ18ir
    FypebuExOQKBgBIwfQjLasuJo2RaXBzo2XOWz85kbVyX64QJTGcGjbcv0XyCre+5
    eHSyhesRT6VPhGE0ZGyTvE9TZHbBFrP7hhjepdJxaVByB135jqkjFcRJOBzifUnU
    NjTbbmIdxB2ZdeKLRJBWwKGVtCIWHRLz4n0QWTaAOu1AKMeDhAulq6vzAoGAYc2k
    ac7aBRSBKIwczNfb/DqVpsBHm4Tw18zVVZoySNisppU76LdfRAl8fZ3pkmXWLeT5
    qY1qBTjh6hGcUJv2cJFO1VRt4VEDzqw1++BhKFTYBuXvO4xcSBFkYKj7hz0mSvD7
    y9elV+tmqGXBaMriYCojvKEtRC0QGfbONVTbkxkCgYEA1/bGbrfgbInCHaiRR7s1
    L+nwHNjd1Cafr5fy3wstbiEmFROz8klzBNQM1uwdqAwd/ctpWxHZD69LWgA9YKJf
    MM2MbzlcfPismNPMVXx+ffVZ5OfOwrIamykaWbCrzsTGlTCl97Q94yxAlQBR+DES
    EuKDKKRuVE8ldNP3KPeOLrU=
    -----END PRIVATE KEY-----
  quay_ca_file: |
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIUJO+I96B/S5jwC3/oXSaDw2qwdTYwDQYJKoZIhvcNAQEL
    BQAwWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NMQVcxEDAOBgNVBAcMB1dS
    T0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0d2FyZUZhY3RvcnkwHhcN
    MjEwNzE5MTIyNzEyWhcNMzEwNzE3MTIyNzEyWjBYMQswCQYDVQQGEwJQTDEQMA4G
    A1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwcRWxhc3Rp
    Y3NlYXJjaFNvZnR3YXJlRmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALPnjujuGSDbh8sf+UaKShU5j5W9mR10j24uQb2mRX/jQJIDiZqG+w63
    uUveG6v5zntmdiq0Kvt7Lg4drF2CcTHrLgc8VssSwbLLt7U96xGTU44d0lQB0Aad
    L8yH+fOoqGwp96qCkAkEJ7gD2YStug9hZTVzME55AA+Y/LtEovtgMmGmWKsQ3EG0
    vxtvFeXsDk0KCQBvcYOAUU3r1IqYq17WNh+BKPWDdOC+BlIs6YKInT580UD9Zz5l
    3Ot1SqfWQp5eZcZBeqzNQj5ZmUOWhhURbT0ArtQKHMN8ogNbLMWPrQDof+sHJuOR
    l8VzxB8xqpJnnjic8AyMXAlfdab5DcUCAwEAAaNTMFEwHQYDVR0OBBYEFK4SopxI
    Pwqjxnky2DgMd2PWVi36MB8GA1UdIwQYMBaAFK4SopxIPwqjxnky2DgMd2PWVi36
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHYJNv7lFnL6RYb0
    uKf4ic1h8txu+/dhruzKcvQjHjheBESgdC9W+XdoHM4MiDyvNvVA+rtsDMtPioSc
    7pIhP2+gE2YsWb5mfp5hc5eXKSKMnmLS34HD0lHMv0ZG/vRIsijuFa1qNjYm4rBQ
    4IZtChcG+rnmKf5tJvRyZdCbJQmtsW6Jhpioyrrw6bvhyQUVOoktR0e2nGtmHcLh
    Qh+BhvraCd8eYN4jYluK5ljEFsMruikyXtol2p2MjnKllT31f0UcteVyFkpeaVgE
    mc+49SQV18rOY3LUMRNBddcWqDVX/rk3IyTugw/7sYycJb1+xJoFEy6+GmH2DF0R
    cYmloZg=
    -----END CERTIFICATE-----
  quay_db_ca_file: |
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIUJO+I96B/S5jwC3/oXSaDw2qwdTYwDQYJKoZIhvcNAQEL
    BQAwWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NMQVcxEDAOBgNVBAcMB1dS
    T0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0d2FyZUZhY3RvcnkwHhcN
    MjEwNzE5MTIyNzEyWhcNMzEwNzE3MTIyNzEyWjBYMQswCQYDVQQGEwJQTDEQMA4G
    A1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwcRWxhc3Rp
    Y3NlYXJjaFNvZnR3YXJlRmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALPnjujuGSDbh8sf+UaKShU5j5W9mR10j24uQb2mRX/jQJIDiZqG+w63
    uUveG6v5zntmdiq0Kvt7Lg4drF2CcTHrLgc8VssSwbLLt7U96xGTU44d0lQB0Aad
    L8yH+fOoqGwp96qCkAkEJ7gD2YStug9hZTVzME55AA+Y/LtEovtgMmGmWKsQ3EG0
    vxtvFeXsDk0KCQBvcYOAUU3r1IqYq17WNh+BKPWDdOC+BlIs6YKInT580UD9Zz5l
    3Ot1SqfWQp5eZcZBeqzNQj5ZmUOWhhURbT0ArtQKHMN8ogNbLMWPrQDof+sHJuOR
    l8VzxB8xqpJnnjic8AyMXAlfdab5DcUCAwEAAaNTMFEwHQYDVR0OBBYEFK4SopxI
    Pwqjxnky2DgMd2PWVi36MB8GA1UdIwQYMBaAFK4SopxIPwqjxnky2DgMd2PWVi36
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHYJNv7lFnL6RYb0
    uKf4ic1h8txu+/dhruzKcvQjHjheBESgdC9W+XdoHM4MiDyvNvVA+rtsDMtPioSc
    7pIhP2+gE2YsWb5mfp5hc5eXKSKMnmLS34HD0lHMv0ZG/vRIsijuFa1qNjYm4rBQ
    4IZtChcG+rnmKf5tJvRyZdCbJQmtsW6Jhpioyrrw6bvhyQUVOoktR0e2nGtmHcLh
    Qh+BhvraCd8eYN4jYluK5ljEFsMruikyXtol2p2MjnKllT31f0UcteVyFkpeaVgE
    mc+49SQV18rOY3LUMRNBddcWqDVX/rk3IyTugw/7sYycJb1+xJoFEy6+GmH2DF0R
    cYmloZg=
    -----END CERTIFICATE-----
  clair_cert_file: |
    -----BEGIN CERTIFICATE-----
    MIIDSjCCAjICFEritoVlMkRRgARbHgCp63+HRYn5MA0GCSqGSIb3DQEBCwUAMFgx
    CzAJBgNVBAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFX
    MSUwIwYDVQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcx
    OTEyMjcxM1oXDTMxMDcxNzEyMjcxM1owazELMAkGA1UEBhMCUEwxEDAOBgNVBAgM
    B1dST0NMQVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFy
    Y2hTb2Z0d2FyZUZhY3RvcnkxETAPBgNVBAMMCHF1YXkuZGV2MIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwESjAJqQ6cnwDyoKzTZ8benASm/Yg89BITis
    Nc6zOo2PY8Lq42UsVX/k3agIfedx0vCzgatto/dk8WwvWyt9nbPYzEC5Duy0vURg
    PUPMM3/65DRcOrlFuqumhRbb0FsKbuRNdlQtDXvGioC46fm3zeRlBR/fxI8AU7pu
    w9Le0Dr27blDfHi1/9ikprar0TjHWzbrv2ONTGEjL3noqSfmaybGItGG+6KXACwx
    2w7xiw/bEuD7iqlrwTqpe0hUkAIzhd/aiXcK8SKccCr8oAZJgAqSMLlsFn3zmYU4
    J4+l8ktPBvJ4JiavnMhUM6vhgqkotq9D1lUAtsxxAoXpZqE5xwIDAQABMA0GCSqG
    SIb3DQEBCwUAA4IBAQBxjosUCMSbtFawhEr61iVac9UmMwMAvY7tQ23ZA8QTBOhw
    Zh39cJ5phmYZkm+NWIefrNMTFI2CSVs9MKiacWOurbpX1qkfYdF4a5yoKhFdWyuC
    JAa0C3I3RdTXJrbpvoQoqHDmPES07KZiKigksZn2uB0zu/woQjdQS6oFoI7z4q81
    PBdKn7yh6EIVntbCLLCQO1eMGs49NStyvDnY8uQCqUXXKA8BTRYrGgumW8te0g1j
    P/e9Gs8YijnM2dBDugmFg+Ygg/H+z+0TqU+MCeCelHXhPXgjd683CSnnnN7dNFUc
    9WJ/F3dStgvCfwMVthwBo1ZTeaPrvCEhSvJ+MaAI
    -----END CERTIFICATE-----
  clair_key_file: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDARKMAmpDpyfAP
    KgrNNnxt6cBKb9iDz0EhOKw1zrM6jY9jwurjZSxVf+TdqAh953HS8LOBq22j92Tx
    bC9bK32ds9jMQLkO7LS9RGA9Q8wzf/rkNFw6uUW6q6aFFtvQWwpu5E12VC0Ne8aK
    gLjp+bfN5GUFH9/EjwBTum7D0t7QOvbtuUN8eLX/2KSmtqvROMdbNuu/Y41MYSMv
    eeipJ+ZrJsYi0Yb7opcALDHbDvGLD9sS4PuKqWvBOql7SFSQAjOF39qJdwrxIpxw
    KvygBkmACpIwuWwWffOZhTgnj6XyS08G8ngmJq+cyFQzq+GCqSi2r0PWVQC2zHEC
    helmoTnHAgMBAAECggEAOFJi5YRhuvqaxfZs35x8ar40xBlrdYE69P5jBAge3KIn
    RPQOVrqGeC1U39GfWzJ3V3GHRA7xuTx5Z3dnj+93hsDuWzcCfuq8L01eW9QGd3eg
    CUWFVvZ7BKnPx+DgV3Kz5bQfNPCHmhGOIXh/spqiS0ACj7O8mxnA4MYWOGsHNjvt
    onA9hg94Kp29jo1eyfIRR/E+Rs4SvOx2njLHkiTC0nKKwflqFj9ZiV1CWJWpg90N
    jv90RaxdIQ8uhsLj7/cQDAf+Dr2ZblEiTluh+tGrcMgTpSNaQoJi6bHiBlwT9VlK
    jQSPhb0kPGsbBweRTYEkeG7tA91aG5eGtp/Gu0mk4QKBgQDi2L8G/QIkKwMqhDyR
    BjRXgYFNB9TKVEh8jncshhnnbLeTeEzki1XL0x1CEcRnCo5hwsuUo4hPGXfMb+v7
    PKeZu9T9FqQRHaiaw/b5BXOSPkchNGCqxbBzcCeh44+6gtMiG7lw1yzJNhvz1UjI
    wS2xUQcB+F9cE5XIxV+vaSTC/wKBgQDY+kGhhIs1coFAr05SfOrzhHC0BnfHVGIa
    ys9K6a8sXoGVcVz560DtuucLBJPGJCRTQT3sLoPU3m3tQpnW37qA/6yWXVwbngzX
    Fp115ywkRoswlujU3b38maIhlWS51oDl0GDkZOqQvqNQ87ON0gLrvCCtXGvQ18ir
    FypebuExOQKBgBIwfQjLasuJo2RaXBzo2XOWz85kbVyX64QJTGcGjbcv0XyCre+5
    eHSyhesRT6VPhGE0ZGyTvE9TZHbBFrP7hhjepdJxaVByB135jqkjFcRJOBzifUnU
    NjTbbmIdxB2ZdeKLRJBWwKGVtCIWHRLz4n0QWTaAOu1AKMeDhAulq6vzAoGAYc2k
    ac7aBRSBKIwczNfb/DqVpsBHm4Tw18zVVZoySNisppU76LdfRAl8fZ3pkmXWLeT5
    qY1qBTjh6hGcUJv2cJFO1VRt4VEDzqw1++BhKFTYBuXvO4xcSBFkYKj7hz0mSvD7
    y9elV+tmqGXBaMriYCojvKEtRC0QGfbONVTbkxkCgYEA1/bGbrfgbInCHaiRR7s1
    L+nwHNjd1Cafr5fy3wstbiEmFROz8klzBNQM1uwdqAwd/ctpWxHZD69LWgA9YKJf
    MM2MbzlcfPismNPMVXx+ffVZ5OfOwrIamykaWbCrzsTGlTCl97Q94yxAlQBR+DES
    EuKDKKRuVE8ldNP3KPeOLrU=
    -----END PRIVATE KEY-----
  clair_ca_files: |
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIUJO+I96B/S5jwC3/oXSaDw2qwdTYwDQYJKoZIhvcNAQEL
    BQAwWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NMQVcxEDAOBgNVBAcMB1dS
    T0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0d2FyZUZhY3RvcnkwHhcN
    MjEwNzE5MTIyNzEyWhcNMzEwNzE3MTIyNzEyWjBYMQswCQYDVQQGEwJQTDEQMA4G
    A1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwcRWxhc3Rp
    Y3NlYXJjaFNvZnR3YXJlRmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALPnjujuGSDbh8sf+UaKShU5j5W9mR10j24uQb2mRX/jQJIDiZqG+w63
    uUveG6v5zntmdiq0Kvt7Lg4drF2CcTHrLgc8VssSwbLLt7U96xGTU44d0lQB0Aad
    L8yH+fOoqGwp96qCkAkEJ7gD2YStug9hZTVzME55AA+Y/LtEovtgMmGmWKsQ3EG0
    vxtvFeXsDk0KCQBvcYOAUU3r1IqYq17WNh+BKPWDdOC+BlIs6YKInT580UD9Zz5l
    3Ot1SqfWQp5eZcZBeqzNQj5ZmUOWhhURbT0ArtQKHMN8ogNbLMWPrQDof+sHJuOR
    l8VzxB8xqpJnnjic8AyMXAlfdab5DcUCAwEAAaNTMFEwHQYDVR0OBBYEFK4SopxI
    Pwqjxnky2DgMd2PWVi36MB8GA1UdIwQYMBaAFK4SopxIPwqjxnky2DgMd2PWVi36
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHYJNv7lFnL6RYb0
    uKf4ic1h8txu+/dhruzKcvQjHjheBESgdC9W+XdoHM4MiDyvNvVA+rtsDMtPioSc
    7pIhP2+gE2YsWb5mfp5hc5eXKSKMnmLS34HD0lHMv0ZG/vRIsijuFa1qNjYm4rBQ
    4IZtChcG+rnmKf5tJvRyZdCbJQmtsW6Jhpioyrrw6bvhyQUVOoktR0e2nGtmHcLh
    Qh+BhvraCd8eYN4jYluK5ljEFsMruikyXtol2p2MjnKllT31f0UcteVyFkpeaVgE
    mc+49SQV18rOY3LUMRNBddcWqDVX/rk3IyTugw/7sYycJb1+xJoFEy6+GmH2DF0R
    cYmloZg=
    -----END CERTIFICATE-----
  clair_db_ca_file: |
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIUJO+I96B/S5jwC3/oXSaDw2qwdTYwDQYJKoZIhvcNAQEL
    BQAwWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NMQVcxEDAOBgNVBAcMB1dS
    T0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0d2FyZUZhY3RvcnkwHhcN
    MjEwNzE5MTIyNzEyWhcNMzEwNzE3MTIyNzEyWjBYMQswCQYDVQQGEwJQTDEQMA4G
    A1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwcRWxhc3Rp
    Y3NlYXJjaFNvZnR3YXJlRmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALPnjujuGSDbh8sf+UaKShU5j5W9mR10j24uQb2mRX/jQJIDiZqG+w63
    uUveG6v5zntmdiq0Kvt7Lg4drF2CcTHrLgc8VssSwbLLt7U96xGTU44d0lQB0Aad
    L8yH+fOoqGwp96qCkAkEJ7gD2YStug9hZTVzME55AA+Y/LtEovtgMmGmWKsQ3EG0
    vxtvFeXsDk0KCQBvcYOAUU3r1IqYq17WNh+BKPWDdOC+BlIs6YKInT580UD9Zz5l
    3Ot1SqfWQp5eZcZBeqzNQj5ZmUOWhhURbT0ArtQKHMN8ogNbLMWPrQDof+sHJuOR
    l8VzxB8xqpJnnjic8AyMXAlfdab5DcUCAwEAAaNTMFEwHQYDVR0OBBYEFK4SopxI
    Pwqjxnky2DgMd2PWVi36MB8GA1UdIwQYMBaAFK4SopxIPwqjxnky2DgMd2PWVi36
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHYJNv7lFnL6RYb0
    uKf4ic1h8txu+/dhruzKcvQjHjheBESgdC9W+XdoHM4MiDyvNvVA+rtsDMtPioSc
    7pIhP2+gE2YsWb5mfp5hc5eXKSKMnmLS34HD0lHMv0ZG/vRIsijuFa1qNjYm4rBQ
    4IZtChcG+rnmKf5tJvRyZdCbJQmtsW6Jhpioyrrw6bvhyQUVOoktR0e2nGtmHcLh
    Qh+BhvraCd8eYN4jYluK5ljEFsMruikyXtol2p2MjnKllT31f0UcteVyFkpeaVgE
    mc+49SQV18rOY3LUMRNBddcWqDVX/rk3IyTugw/7sYycJb1+xJoFEy6+GmH2DF0R
    cYmloZg=
    -----END CERTIFICATE-----
  postgres_ssl_crt: |
    -----BEGIN CERTIFICATE-----
    MIIDSjCCAjICFEritoVlMkRRgARbHgCp63+HRYn5MA0GCSqGSIb3DQEBCwUAMFgx
    CzAJBgNVBAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFX
    MSUwIwYDVQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcx
    OTEyMjcxM1oXDTMxMDcxNzEyMjcxM1owazELMAkGA1UEBhMCUEwxEDAOBgNVBAgM
    B1dST0NMQVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFy
    Y2hTb2Z0d2FyZUZhY3RvcnkxETAPBgNVBAMMCHF1YXkuZGV2MIIBIjANBgkqhkiG
    9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwESjAJqQ6cnwDyoKzTZ8benASm/Yg89BITis
    Nc6zOo2PY8Lq42UsVX/k3agIfedx0vCzgatto/dk8WwvWyt9nbPYzEC5Duy0vURg
    PUPMM3/65DRcOrlFuqumhRbb0FsKbuRNdlQtDXvGioC46fm3zeRlBR/fxI8AU7pu
    w9Le0Dr27blDfHi1/9ikprar0TjHWzbrv2ONTGEjL3noqSfmaybGItGG+6KXACwx
    2w7xiw/bEuD7iqlrwTqpe0hUkAIzhd/aiXcK8SKccCr8oAZJgAqSMLlsFn3zmYU4
    J4+l8ktPBvJ4JiavnMhUM6vhgqkotq9D1lUAtsxxAoXpZqE5xwIDAQABMA0GCSqG
    SIb3DQEBCwUAA4IBAQBxjosUCMSbtFawhEr61iVac9UmMwMAvY7tQ23ZA8QTBOhw
    Zh39cJ5phmYZkm+NWIefrNMTFI2CSVs9MKiacWOurbpX1qkfYdF4a5yoKhFdWyuC
    JAa0C3I3RdTXJrbpvoQoqHDmPES07KZiKigksZn2uB0zu/woQjdQS6oFoI7z4q81
    PBdKn7yh6EIVntbCLLCQO1eMGs49NStyvDnY8uQCqUXXKA8BTRYrGgumW8te0g1j
    P/e9Gs8YijnM2dBDugmFg+Ygg/H+z+0TqU+MCeCelHXhPXgjd683CSnnnN7dNFUc
    9WJ/F3dStgvCfwMVthwBo1ZTeaPrvCEhSvJ+MaAI
    -----END CERTIFICATE-----
  postgres_ssl_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDARKMAmpDpyfAP
    KgrNNnxt6cBKb9iDz0EhOKw1zrM6jY9jwurjZSxVf+TdqAh953HS8LOBq22j92Tx
    bC9bK32ds9jMQLkO7LS9RGA9Q8wzf/rkNFw6uUW6q6aFFtvQWwpu5E12VC0Ne8aK
    gLjp+bfN5GUFH9/EjwBTum7D0t7QOvbtuUN8eLX/2KSmtqvROMdbNuu/Y41MYSMv
    eeipJ+ZrJsYi0Yb7opcALDHbDvGLD9sS4PuKqWvBOql7SFSQAjOF39qJdwrxIpxw
    KvygBkmACpIwuWwWffOZhTgnj6XyS08G8ngmJq+cyFQzq+GCqSi2r0PWVQC2zHEC
    helmoTnHAgMBAAECggEAOFJi5YRhuvqaxfZs35x8ar40xBlrdYE69P5jBAge3KIn
    RPQOVrqGeC1U39GfWzJ3V3GHRA7xuTx5Z3dnj+93hsDuWzcCfuq8L01eW9QGd3eg
    CUWFVvZ7BKnPx+DgV3Kz5bQfNPCHmhGOIXh/spqiS0ACj7O8mxnA4MYWOGsHNjvt
    onA9hg94Kp29jo1eyfIRR/E+Rs4SvOx2njLHkiTC0nKKwflqFj9ZiV1CWJWpg90N
    jv90RaxdIQ8uhsLj7/cQDAf+Dr2ZblEiTluh+tGrcMgTpSNaQoJi6bHiBlwT9VlK
    jQSPhb0kPGsbBweRTYEkeG7tA91aG5eGtp/Gu0mk4QKBgQDi2L8G/QIkKwMqhDyR
    BjRXgYFNB9TKVEh8jncshhnnbLeTeEzki1XL0x1CEcRnCo5hwsuUo4hPGXfMb+v7
    PKeZu9T9FqQRHaiaw/b5BXOSPkchNGCqxbBzcCeh44+6gtMiG7lw1yzJNhvz1UjI
    wS2xUQcB+F9cE5XIxV+vaSTC/wKBgQDY+kGhhIs1coFAr05SfOrzhHC0BnfHVGIa
    ys9K6a8sXoGVcVz560DtuucLBJPGJCRTQT3sLoPU3m3tQpnW37qA/6yWXVwbngzX
    Fp115ywkRoswlujU3b38maIhlWS51oDl0GDkZOqQvqNQ87ON0gLrvCCtXGvQ18ir
    FypebuExOQKBgBIwfQjLasuJo2RaXBzo2XOWz85kbVyX64QJTGcGjbcv0XyCre+5
    eHSyhesRT6VPhGE0ZGyTvE9TZHbBFrP7hhjepdJxaVByB135jqkjFcRJOBzifUnU
    NjTbbmIdxB2ZdeKLRJBWwKGVtCIWHRLz4n0QWTaAOu1AKMeDhAulq6vzAoGAYc2k
    ac7aBRSBKIwczNfb/DqVpsBHm4Tw18zVVZoySNisppU76LdfRAl8fZ3pkmXWLeT5
    qY1qBTjh6hGcUJv2cJFO1VRt4VEDzqw1++BhKFTYBuXvO4xcSBFkYKj7hz0mSvD7
    y9elV+tmqGXBaMriYCojvKEtRC0QGfbONVTbkxkCgYEA1/bGbrfgbInCHaiRR7s1
    L+nwHNjd1Cafr5fy3wstbiEmFROz8klzBNQM1uwdqAwd/ctpWxHZD69LWgA9YKJf
    MM2MbzlcfPismNPMVXx+ffVZ5OfOwrIamykaWbCrzsTGlTCl97Q94yxAlQBR+DES
    EuKDKKRuVE8ldNP3KPeOLrU=
    -----END PRIVATE KEY-----
  postgres_ssl_ca: |
    -----BEGIN CERTIFICATE-----
    MIIDkTCCAnmgAwIBAgIUJO+I96B/S5jwC3/oXSaDw2qwdTYwDQYJKoZIhvcNAQEL
    BQAwWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NMQVcxEDAOBgNVBAcMB1dS
    T0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0d2FyZUZhY3RvcnkwHhcN
    MjEwNzE5MTIyNzEyWhcNMzEwNzE3MTIyNzEyWjBYMQswCQYDVQQGEwJQTDEQMA4G
    A1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwcRWxhc3Rp
    Y3NlYXJjaFNvZnR3YXJlRmFjdG9yeTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALPnjujuGSDbh8sf+UaKShU5j5W9mR10j24uQb2mRX/jQJIDiZqG+w63
    uUveG6v5zntmdiq0Kvt7Lg4drF2CcTHrLgc8VssSwbLLt7U96xGTU44d0lQB0Aad
    L8yH+fOoqGwp96qCkAkEJ7gD2YStug9hZTVzME55AA+Y/LtEovtgMmGmWKsQ3EG0
    vxtvFeXsDk0KCQBvcYOAUU3r1IqYq17WNh+BKPWDdOC+BlIs6YKInT580UD9Zz5l
    3Ot1SqfWQp5eZcZBeqzNQj5ZmUOWhhURbT0ArtQKHMN8ogNbLMWPrQDof+sHJuOR
    l8VzxB8xqpJnnjic8AyMXAlfdab5DcUCAwEAAaNTMFEwHQYDVR0OBBYEFK4SopxI
    Pwqjxnky2DgMd2PWVi36MB8GA1UdIwQYMBaAFK4SopxIPwqjxnky2DgMd2PWVi36
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAHYJNv7lFnL6RYb0
    uKf4ic1h8txu+/dhruzKcvQjHjheBESgdC9W+XdoHM4MiDyvNvVA+rtsDMtPioSc
    7pIhP2+gE2YsWb5mfp5hc5eXKSKMnmLS34HD0lHMv0ZG/vRIsijuFa1qNjYm4rBQ
    4IZtChcG+rnmKf5tJvRyZdCbJQmtsW6Jhpioyrrw6bvhyQUVOoktR0e2nGtmHcLh
    Qh+BhvraCd8eYN4jYluK5ljEFsMruikyXtol2p2MjnKllT31f0UcteVyFkpeaVgE
    mc+49SQV18rOY3LUMRNBddcWqDVX/rk3IyTugw/7sYycJb1+xJoFEy6+GmH2DF0R
    cYmloZg=
    -----END CERTIFICATE-----
