inventory_name: dev
ansible_ssh_user: centos
ansible_become_pass: T$est089

drop_quay_db: true
delete_old_quay_config: true
remove_all_folders: true

remove_redis_container: true
remove_quay_container: true
remove_clair_container: true
remove_postgres_container: true
remove_quayconfig_container: true

quay_hostname: quay.dev
quay_runtime_user: root
quay_vm_user: root
quay_initial_superuser_username: yoda
quay_initial_superuser_email: yoda@quay.dev

postgres_ssl_mode: false
prefered_storage: default

is_quay: false
data_dir_base: /var/data
quay_data_dir: /var/data/quay
quay_repomirror_storage_dir: /var/data/repomirror
quay_setup_name: quayconfig
quay_repomirror_feature: false
quay_db_dbname: quay_db
quay_db_username: quay_user
quay_db_admin_username: postgres
quay_redis_port: 6379
quay_db_port: 5432
quay_db_admin_password: "{{ secrets.quay_db_admin_password }}"
quay_db_password: "{{ secrets.quay_db_password }}"
quay_registry_password: "{{ secrets.quay_registry_password }}"
quay_logo_file: "../../files/common/custom-logo.svg"

is_clair: false
clair_runtime_user: root
clair_hostname: clair.dev
clair_force_new_key: true
clair_db_username: clair_user
clair_db_admin_username: postgres
clair_db_dbname: clair_db
clair_db_port: 5432
clair_data_dir: /var/data/clair
clair_proxy_mode: false
# clair_proxy_name:
# clair_proxy_port:

image_registry: quay.io
image_registry_user: dpawlik

postgres_image: "rhscl/postgresql-96-rhel7"
redis_image: "rhscl/redis-32-rhel7:3.2"
quay_image: "{{ image_registry }}/redhat/quay:v3.3.4"
clair_image: "{{ image_registry }}/redhat/clair-jwt:v3.3.4"
test_image: "registry.access.redhat.com/ubi8/ubi-minimal:8.0"
test_image_local: "{{ quay_hostname }}/ubi8/ubi-minimal:8.0"
test_image_tag: "8.0"
test_image_api: "ubi8/ubi-minimal"
test_skip_login_pull: true

quay_test_robot_name: ubi8+test_robot
quay_test_robot_password: 2M8ILGF6GZST6RFSINNGCMZBZUHGKPDY6Y50MIB11E7KY783XKS6AMYKQSFOW2JS
quay_system_test_manifest: sha256:90e7a8c15504099bd3a6656ad5f75b26c25822fba6d09d3b067f24c4c6faf4ba
quay_system_test_bearer: zXhBoyJLD4ErnP4Slh0fQWTVETK0yqF1eRW6XyAD

quay_cert_file: "{{ certs.quay_cert_file }}"
quay_key_file: "{{ certs.quay_key_file }}"
quay_ca_file: "{{ certs.quay_ca_file }}"
quay_db_ca_file: "{{ certs.postgres_ssl_ca }}"

clair_cert_file: "{{ certs.clair_cert_file }}"
clair_key_file: "{{ certs.clair_key_file }}"
clair_ca_files: "{{ certs.clair_ca_files }}"
clair_db_ca_file: "{{ certs.postgres_ssl_ca }}"

postgres_ssl_crt: "{{ certs.postgres_ssl_crt }}"
postgres_ssl_key: "{{ certs.postgres_ssl_key }}"
postgres_ssl_ca: "{{ certs.postgres_ssl_ca }}"

# quay_s3_cert_file: ""
# quay_ldap_cert_file: ""
# quay_s3_cert_name: ""
# quay_ldap_cert_name: ""

secrets:
  quay_initial_superuser_password: mypassword
  quay_db_admin_password: mypassword
  quay_setup_password: mypassword2
  quay_db_password: mypassword3
  quay_registry_password: mypassword4
  clair_db_admin_password: mypassword5
  clair_db_password: mypassword6
  quay_redis_password: mypassword7
  azure_account_key: mypassword8
  azure_sas_token: mypassword9
  ldap_password: mypassword10

certs:
  quay_cert_file: |
    -----BEGIN CERTIFICATE-----
    MIIDUDCCAjgCCQCcFBv7onkxRzANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJQ
    TDEQMA4GA1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwc
    RWxhc3RpY3NlYXJjaFNvZnR3YXJlRmFjdG9yeTAeFw0yMTA3MTYwODU2NDNaFw0z
    MTA3MTQwODU2NDNaMHwxCzAJBgNVBAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAw
    DgYDVQQHDAdXUk9DTEFXMSUwIwYDVQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVG
    YWN0b3J5MSIwIAYDVQQDDBllbGFzdGljc2VhcmNoLnNmdGVzdHMuY29tMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApDOCTd2S+KgEO6zk5WSN7k8WRqGk
    FosuVW885xvAUAaX4G41vflKr6oesVOsSFyU4wL+Zfbpaf5AZT9qK+c0TBwk23wG
    WPj+z2nnCnTGcHpDuGFvXYvJIWpJGPAdrdivfBDTgSYQzCMXhb31SC5MOsS/41yX
    3Skw3P8Pc6KGJKP7ClVH90/HKDTmnXmLzD72KSLzt5UngV6FOHhGlI9d2UciRYi1
    tqraTWNbFRoA642MTBjG66obXOwS9YNwrA0KyklHwiknFi7GBnLuZIasExYjNamV
    3JJ7oDq6E+UtpFZtvx+CVD+OcLp0JVgAwWxgYfsAk0SibBpyZL+IoURhnQIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4IBAQDD7Zha/GRCNUt1AX4IMzooQZAUimcOuGCN8+GB
    3F0jR1sVuGS5oDqnrwEKNwIrkJHX4zm22qbGB2PZLIj93+EJvlzXuXiPH2V+UTWR
    WzuxYZwVScVj+h4w1x+/Xdjj1s0NlZ3iQ9HirHW+IXAGzVVU9PtdggLvgS4PhvWm
    /wMueYRoDeWhl+9RpIudCAdlDtWWDy9LKPDOpY2pkLEpWZrruY1K4Kv3KouYLNZw
    7apYEa59un09QIae1Ema/KMTlDPswiq+V720Jlq/K22zgeY7dHMMb1BpbIECAFss
    gnn3nkmuTYTd73BVmr75+6HhXkkeTqob0jcb8MF1W27HAu2z
    -----END CERTIFICATE-----

  quay_key_file: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkM4JN3ZL4qAQ7
    rOTlZI3uTxZGoaQWiy5VbzznG8BQBpfgbjW9+Uqvqh6xU6xIXJTjAv5l9ulp/kBl
    P2or5zRMHCTbfAZY+P7PaecKdMZwekO4YW9di8khakkY8B2t2K98ENOBJhDMIxeF
    vfVILkw6xL/jXJfdKTDc/w9zooYko/sKVUf3T8coNOadeYvMPvYpIvO3lSeBXoU4
    eEaUj13ZRyJFiLW2qtpNY1sVGgDrjYxMGMbrqhtc7BL1g3CsDQrKSUfCKScWLsYG
    cu5khqwTFiM1qZXcknugOroT5S2kVm2/H4JUP45wunQlWADBbGBh+wCTRKJsGnJk
    v4ihRGGdAgMBAAECggEAbNPmzQzJ2BwjkhmpK5BVsVihfvaq9nYQo3cyekoeT+vO
    xWTGIb8UDRFHfmfii6Mw2rSlP5dCZImqzHAXQjneo4MTupSc8GM3Huklw/xZeTrP
    n2iUkv+OsqLrB6g9Q3eV9zh/td0wzNuFP5MC+nAU/e5g76Py0xX12MMDzrQtDCLC
    /NmjLxy9TnRZtR7+SIroYc1Z7AZv0RBc9Rz8YwJL/8UByE8GLEmaWJFzNK3NQt/s
    1V7pRJY/C0S53/KJxOhPOJ4Wc8dZaSa6zBMPmiRg27+wXpY1OALc/DR5vmHTAyQi
    ZbPSbaVirKhRqVhusOr3r3PDrpigzBgpOId588lC0QKBgQDN9Gz3kN/C/d2gKCbJ
    vjNgzhvtvIoyAIs9BF0AuFabGSpz82WcayrnPtkMz7f9UFQLDfLM1Bdw+NoZq95W
    48S5F1emE0+XT9vmmA0hLR2PT+Yf7ULZWrVkYRe5St0bidvlwQG0k4yJuVmAu4ox
    EnBS+Khs7ySkeLlrQMaHwxq+lwKBgQDMGcUj3NrU7Q9Y4pzJabiYIht87nmq8E9e
    VOlPDfLwDJtQ9Niuhzdk1xHW2f5B1xMIRbGegamzUR4Jku/Yvg/zZNUchVjuDD7/
    2pJuS/fRND/m0IH3bnYD8btPIab1GcC6bqBcX0/6cv5q55xl5RpRq4w49USbf2KB
    X1SHuH6b6wKBgQDCPg8vhnGjxC7sSDIc/8gROxLYK4PjGOQ5jg3xCeqUqS2C4kIp
    PmHea0XmcVpEDSjWrDccu8PIBswcfh5asMLvFnbR6VCdkvIBD9MCQTyp119hKTJt
    MMH3hCMN3O+gc2rzzA7Bso9PrYIeicIR+iP5/Q9Mfld+z2WBJDyZ+ocUzQKBgHpE
    RdECESXVDYiV2I7gAnFAnW7t/XzlkOZVv55YINyk8LZCtzt2TTzfihRHawVOLlya
    Q5lM27hMM85Qc9ZHpY6NLQ105J1WQLdM3MOuRrrQric7aWAskA401ZzF8BqMXuRQ
    OUic4HCMStUIAq0X3fhm6A2HAJ6WZRBTZ3QWleIZAoGAdZbSYYPF74QKRuzyfq0f
    gf4kaOMDQh2p+N4/GaaB1Xp/geMrvt9/bsAQHsTDSpb/6Abh3cuAA1IebTDd4027
    Jem8nflEDp/1chJWdWVe2H+ArtFgXy9ZjdIUpM5fTFHDtqanpncOFOzLinx/1kTX
    IHnEwdqGgjPfSgdYaEYt5e8=
    -----END PRIVATE KEY-----

  quay_ca_file: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIJAMIEExxt0wjsMA0GCSqGSIb3DQEBCwUAMFgxCzAJBgNV
    BAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFXMSUwIwYD
    VQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcxNjA4NTYz
    N1oXDTMxMDcxNDA4NTYzN1owWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NM
    QVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0
    d2FyZUZhY3RvcnkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKXjbt
    MTEV4IzZiFq1N+DKiSQDubW9MNGrzkgrBzrso1K3UwTImTsAgzUH/8WHyQPGQ1o7
    o3v8VjuPzhuxlkgZU6A2sOVpqorZSyWjWM24DsNfJg45l+PoAzaKOoV1WSmCfSoQ
    NkyCAR4h8jzgwZUPKEfr6fY6Rv2a2WK7muCggJfiWweec1aQg2R0lNiQ8DRhQDPg
    U7EJdLMz61HWI8/TFEQIVZKPtkUBRR5uovZ+pXjtkNR6yyIP0cvfhXO4n4S474wx
    OOg5DevdFcXvKSJ5rvti502fJuma38KllHEvaHFEurECke3bPna6KzoG9WzrULc4
    5hDSvWO8D4adNhMJAgMBAAGjUDBOMB0GA1UdDgQWBBTJFta/f7YOieENO/z/DmBX
    OwbwQDAfBgNVHSMEGDAWgBTJFta/f7YOieENO/z/DmBXOwbwQDAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQALr9HynXIiICt0JjHs5KmzYcz325QkDyHL
    OC/VVY2JHLzrH8JjRN/itF2V03Snj7NSieG1q/N/Z2gt/jVMyQE1R4bW4bmMnIZM
    9jtaUgi5y/HOPpIYMfIB0PyYUsPzJT0JECc6x+kXkrzr31TJod65IoPVSMi+b5Oy
    uXOh1BLG/+HyY39cMbDCznoY9t7AprGZcDfb+Psv/9wwFUnk4ke6uSqhDalTV/fA
    uTQ/QNO1330Wb8xq3xKgPXcndszEwD6OVvU4Dl6S4gIEeopFQHsJWBkVuFKs2rIw
    2C4WVzfxoWOSqH0SMxDQorFIWMgphb4cnhmS8OW7zDR7YuvMU6Yz
    -----END CERTIFICATE-----

  quay_db_ca_file: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIJAMIEExxt0wjsMA0GCSqGSIb3DQEBCwUAMFgxCzAJBgNV
    BAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFXMSUwIwYD
    VQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcxNjA4NTYz
    N1oXDTMxMDcxNDA4NTYzN1owWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NM
    QVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0
    d2FyZUZhY3RvcnkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKXjbt
    MTEV4IzZiFq1N+DKiSQDubW9MNGrzkgrBzrso1K3UwTImTsAgzUH/8WHyQPGQ1o7
    o3v8VjuPzhuxlkgZU6A2sOVpqorZSyWjWM24DsNfJg45l+PoAzaKOoV1WSmCfSoQ
    NkyCAR4h8jzgwZUPKEfr6fY6Rv2a2WK7muCggJfiWweec1aQg2R0lNiQ8DRhQDPg
    U7EJdLMz61HWI8/TFEQIVZKPtkUBRR5uovZ+pXjtkNR6yyIP0cvfhXO4n4S474wx
    OOg5DevdFcXvKSJ5rvti502fJuma38KllHEvaHFEurECke3bPna6KzoG9WzrULc4
    5hDSvWO8D4adNhMJAgMBAAGjUDBOMB0GA1UdDgQWBBTJFta/f7YOieENO/z/DmBX
    OwbwQDAfBgNVHSMEGDAWgBTJFta/f7YOieENO/z/DmBXOwbwQDAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQALr9HynXIiICt0JjHs5KmzYcz325QkDyHL
    OC/VVY2JHLzrH8JjRN/itF2V03Snj7NSieG1q/N/Z2gt/jVMyQE1R4bW4bmMnIZM
    9jtaUgi5y/HOPpIYMfIB0PyYUsPzJT0JECc6x+kXkrzr31TJod65IoPVSMi+b5Oy
    uXOh1BLG/+HyY39cMbDCznoY9t7AprGZcDfb+Psv/9wwFUnk4ke6uSqhDalTV/fA
    uTQ/QNO1330Wb8xq3xKgPXcndszEwD6OVvU4Dl6S4gIEeopFQHsJWBkVuFKs2rIw
    2C4WVzfxoWOSqH0SMxDQorFIWMgphb4cnhmS8OW7zDR7YuvMU6Yz
    -----END CERTIFICATE-----

  clair_cert_file: |
    -----BEGIN CERTIFICATE-----
    MIIDUDCCAjgCCQCcFBv7onkxRzANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJQ
    TDEQMA4GA1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwc
    RWxhc3RpY3NlYXJjaFNvZnR3YXJlRmFjdG9yeTAeFw0yMTA3MTYwODU2NDNaFw0z
    MTA3MTQwODU2NDNaMHwxCzAJBgNVBAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAw
    DgYDVQQHDAdXUk9DTEFXMSUwIwYDVQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVG
    YWN0b3J5MSIwIAYDVQQDDBllbGFzdGljc2VhcmNoLnNmdGVzdHMuY29tMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApDOCTd2S+KgEO6zk5WSN7k8WRqGk
    FosuVW885xvAUAaX4G41vflKr6oesVOsSFyU4wL+Zfbpaf5AZT9qK+c0TBwk23wG
    WPj+z2nnCnTGcHpDuGFvXYvJIWpJGPAdrdivfBDTgSYQzCMXhb31SC5MOsS/41yX
    3Skw3P8Pc6KGJKP7ClVH90/HKDTmnXmLzD72KSLzt5UngV6FOHhGlI9d2UciRYi1
    tqraTWNbFRoA642MTBjG66obXOwS9YNwrA0KyklHwiknFi7GBnLuZIasExYjNamV
    3JJ7oDq6E+UtpFZtvx+CVD+OcLp0JVgAwWxgYfsAk0SibBpyZL+IoURhnQIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4IBAQDD7Zha/GRCNUt1AX4IMzooQZAUimcOuGCN8+GB
    3F0jR1sVuGS5oDqnrwEKNwIrkJHX4zm22qbGB2PZLIj93+EJvlzXuXiPH2V+UTWR
    WzuxYZwVScVj+h4w1x+/Xdjj1s0NlZ3iQ9HirHW+IXAGzVVU9PtdggLvgS4PhvWm
    /wMueYRoDeWhl+9RpIudCAdlDtWWDy9LKPDOpY2pkLEpWZrruY1K4Kv3KouYLNZw
    7apYEa59un09QIae1Ema/KMTlDPswiq+V720Jlq/K22zgeY7dHMMb1BpbIECAFss
    gnn3nkmuTYTd73BVmr75+6HhXkkeTqob0jcb8MF1W27HAu2z
    -----END CERTIFICATE-----

  clair_key_file: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkM4JN3ZL4qAQ7
    rOTlZI3uTxZGoaQWiy5VbzznG8BQBpfgbjW9+Uqvqh6xU6xIXJTjAv5l9ulp/kBl
    P2or5zRMHCTbfAZY+P7PaecKdMZwekO4YW9di8khakkY8B2t2K98ENOBJhDMIxeF
    vfVILkw6xL/jXJfdKTDc/w9zooYko/sKVUf3T8coNOadeYvMPvYpIvO3lSeBXoU4
    eEaUj13ZRyJFiLW2qtpNY1sVGgDrjYxMGMbrqhtc7BL1g3CsDQrKSUfCKScWLsYG
    cu5khqwTFiM1qZXcknugOroT5S2kVm2/H4JUP45wunQlWADBbGBh+wCTRKJsGnJk
    v4ihRGGdAgMBAAECggEAbNPmzQzJ2BwjkhmpK5BVsVihfvaq9nYQo3cyekoeT+vO
    xWTGIb8UDRFHfmfii6Mw2rSlP5dCZImqzHAXQjneo4MTupSc8GM3Huklw/xZeTrP
    n2iUkv+OsqLrB6g9Q3eV9zh/td0wzNuFP5MC+nAU/e5g76Py0xX12MMDzrQtDCLC
    /NmjLxy9TnRZtR7+SIroYc1Z7AZv0RBc9Rz8YwJL/8UByE8GLEmaWJFzNK3NQt/s
    1V7pRJY/C0S53/KJxOhPOJ4Wc8dZaSa6zBMPmiRg27+wXpY1OALc/DR5vmHTAyQi
    ZbPSbaVirKhRqVhusOr3r3PDrpigzBgpOId588lC0QKBgQDN9Gz3kN/C/d2gKCbJ
    vjNgzhvtvIoyAIs9BF0AuFabGSpz82WcayrnPtkMz7f9UFQLDfLM1Bdw+NoZq95W
    48S5F1emE0+XT9vmmA0hLR2PT+Yf7ULZWrVkYRe5St0bidvlwQG0k4yJuVmAu4ox
    EnBS+Khs7ySkeLlrQMaHwxq+lwKBgQDMGcUj3NrU7Q9Y4pzJabiYIht87nmq8E9e
    VOlPDfLwDJtQ9Niuhzdk1xHW2f5B1xMIRbGegamzUR4Jku/Yvg/zZNUchVjuDD7/
    2pJuS/fRND/m0IH3bnYD8btPIab1GcC6bqBcX0/6cv5q55xl5RpRq4w49USbf2KB
    X1SHuH6b6wKBgQDCPg8vhnGjxC7sSDIc/8gROxLYK4PjGOQ5jg3xCeqUqS2C4kIp
    PmHea0XmcVpEDSjWrDccu8PIBswcfh5asMLvFnbR6VCdkvIBD9MCQTyp119hKTJt
    MMH3hCMN3O+gc2rzzA7Bso9PrYIeicIR+iP5/Q9Mfld+z2WBJDyZ+ocUzQKBgHpE
    RdECESXVDYiV2I7gAnFAnW7t/XzlkOZVv55YINyk8LZCtzt2TTzfihRHawVOLlya
    Q5lM27hMM85Qc9ZHpY6NLQ105J1WQLdM3MOuRrrQric7aWAskA401ZzF8BqMXuRQ
    OUic4HCMStUIAq0X3fhm6A2HAJ6WZRBTZ3QWleIZAoGAdZbSYYPF74QKRuzyfq0f
    gf4kaOMDQh2p+N4/GaaB1Xp/geMrvt9/bsAQHsTDSpb/6Abh3cuAA1IebTDd4027
    Jem8nflEDp/1chJWdWVe2H+ArtFgXy9ZjdIUpM5fTFHDtqanpncOFOzLinx/1kTX
    IHnEwdqGgjPfSgdYaEYt5e8=
    -----END PRIVATE KEY-----

  clair_ca_files: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIJAMIEExxt0wjsMA0GCSqGSIb3DQEBCwUAMFgxCzAJBgNV
    BAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFXMSUwIwYD
    VQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcxNjA4NTYz
    N1oXDTMxMDcxNDA4NTYzN1owWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NM
    QVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0
    d2FyZUZhY3RvcnkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKXjbt
    MTEV4IzZiFq1N+DKiSQDubW9MNGrzkgrBzrso1K3UwTImTsAgzUH/8WHyQPGQ1o7
    o3v8VjuPzhuxlkgZU6A2sOVpqorZSyWjWM24DsNfJg45l+PoAzaKOoV1WSmCfSoQ
    NkyCAR4h8jzgwZUPKEfr6fY6Rv2a2WK7muCggJfiWweec1aQg2R0lNiQ8DRhQDPg
    U7EJdLMz61HWI8/TFEQIVZKPtkUBRR5uovZ+pXjtkNR6yyIP0cvfhXO4n4S474wx
    OOg5DevdFcXvKSJ5rvti502fJuma38KllHEvaHFEurECke3bPna6KzoG9WzrULc4
    5hDSvWO8D4adNhMJAgMBAAGjUDBOMB0GA1UdDgQWBBTJFta/f7YOieENO/z/DmBX
    OwbwQDAfBgNVHSMEGDAWgBTJFta/f7YOieENO/z/DmBXOwbwQDAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQALr9HynXIiICt0JjHs5KmzYcz325QkDyHL
    OC/VVY2JHLzrH8JjRN/itF2V03Snj7NSieG1q/N/Z2gt/jVMyQE1R4bW4bmMnIZM
    9jtaUgi5y/HOPpIYMfIB0PyYUsPzJT0JECc6x+kXkrzr31TJod65IoPVSMi+b5Oy
    uXOh1BLG/+HyY39cMbDCznoY9t7AprGZcDfb+Psv/9wwFUnk4ke6uSqhDalTV/fA
    uTQ/QNO1330Wb8xq3xKgPXcndszEwD6OVvU4Dl6S4gIEeopFQHsJWBkVuFKs2rIw
    2C4WVzfxoWOSqH0SMxDQorFIWMgphb4cnhmS8OW7zDR7YuvMU6Yz
    -----END CERTIFICATE-----
  clair_db_ca_file: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIJAMIEExxt0wjsMA0GCSqGSIb3DQEBCwUAMFgxCzAJBgNV
    BAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFXMSUwIwYD
    VQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcxNjA4NTYz
    N1oXDTMxMDcxNDA4NTYzN1owWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NM
    QVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0
    d2FyZUZhY3RvcnkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKXjbt
    MTEV4IzZiFq1N+DKiSQDubW9MNGrzkgrBzrso1K3UwTImTsAgzUH/8WHyQPGQ1o7
    o3v8VjuPzhuxlkgZU6A2sOVpqorZSyWjWM24DsNfJg45l+PoAzaKOoV1WSmCfSoQ
    NkyCAR4h8jzgwZUPKEfr6fY6Rv2a2WK7muCggJfiWweec1aQg2R0lNiQ8DRhQDPg
    U7EJdLMz61HWI8/TFEQIVZKPtkUBRR5uovZ+pXjtkNR6yyIP0cvfhXO4n4S474wx
    OOg5DevdFcXvKSJ5rvti502fJuma38KllHEvaHFEurECke3bPna6KzoG9WzrULc4
    5hDSvWO8D4adNhMJAgMBAAGjUDBOMB0GA1UdDgQWBBTJFta/f7YOieENO/z/DmBX
    OwbwQDAfBgNVHSMEGDAWgBTJFta/f7YOieENO/z/DmBXOwbwQDAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQALr9HynXIiICt0JjHs5KmzYcz325QkDyHL
    OC/VVY2JHLzrH8JjRN/itF2V03Snj7NSieG1q/N/Z2gt/jVMyQE1R4bW4bmMnIZM
    9jtaUgi5y/HOPpIYMfIB0PyYUsPzJT0JECc6x+kXkrzr31TJod65IoPVSMi+b5Oy
    uXOh1BLG/+HyY39cMbDCznoY9t7AprGZcDfb+Psv/9wwFUnk4ke6uSqhDalTV/fA
    uTQ/QNO1330Wb8xq3xKgPXcndszEwD6OVvU4Dl6S4gIEeopFQHsJWBkVuFKs2rIw
    2C4WVzfxoWOSqH0SMxDQorFIWMgphb4cnhmS8OW7zDR7YuvMU6Yz
    -----END CERTIFICATE-----
  postgres_ssl_crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUDCCAjgCCQCcFBv7onkxRzANBgkqhkiG9w0BAQsFADBYMQswCQYDVQQGEwJQ
    TDEQMA4GA1UECAwHV1JPQ0xBVzEQMA4GA1UEBwwHV1JPQ0xBVzElMCMGA1UECgwc
    RWxhc3RpY3NlYXJjaFNvZnR3YXJlRmFjdG9yeTAeFw0yMTA3MTYwODU2NDNaFw0z
    MTA3MTQwODU2NDNaMHwxCzAJBgNVBAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAw
    DgYDVQQHDAdXUk9DTEFXMSUwIwYDVQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVG
    YWN0b3J5MSIwIAYDVQQDDBllbGFzdGljc2VhcmNoLnNmdGVzdHMuY29tMIIBIjAN
    BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApDOCTd2S+KgEO6zk5WSN7k8WRqGk
    FosuVW885xvAUAaX4G41vflKr6oesVOsSFyU4wL+Zfbpaf5AZT9qK+c0TBwk23wG
    WPj+z2nnCnTGcHpDuGFvXYvJIWpJGPAdrdivfBDTgSYQzCMXhb31SC5MOsS/41yX
    3Skw3P8Pc6KGJKP7ClVH90/HKDTmnXmLzD72KSLzt5UngV6FOHhGlI9d2UciRYi1
    tqraTWNbFRoA642MTBjG66obXOwS9YNwrA0KyklHwiknFi7GBnLuZIasExYjNamV
    3JJ7oDq6E+UtpFZtvx+CVD+OcLp0JVgAwWxgYfsAk0SibBpyZL+IoURhnQIDAQAB
    MA0GCSqGSIb3DQEBCwUAA4IBAQDD7Zha/GRCNUt1AX4IMzooQZAUimcOuGCN8+GB
    3F0jR1sVuGS5oDqnrwEKNwIrkJHX4zm22qbGB2PZLIj93+EJvlzXuXiPH2V+UTWR
    WzuxYZwVScVj+h4w1x+/Xdjj1s0NlZ3iQ9HirHW+IXAGzVVU9PtdggLvgS4PhvWm
    /wMueYRoDeWhl+9RpIudCAdlDtWWDy9LKPDOpY2pkLEpWZrruY1K4Kv3KouYLNZw
    7apYEa59un09QIae1Ema/KMTlDPswiq+V720Jlq/K22zgeY7dHMMb1BpbIECAFss
    gnn3nkmuTYTd73BVmr75+6HhXkkeTqob0jcb8MF1W27HAu2z
    -----END CERTIFICATE-----
  postgres_ssl_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCkM4JN3ZL4qAQ7
    rOTlZI3uTxZGoaQWiy5VbzznG8BQBpfgbjW9+Uqvqh6xU6xIXJTjAv5l9ulp/kBl
    P2or5zRMHCTbfAZY+P7PaecKdMZwekO4YW9di8khakkY8B2t2K98ENOBJhDMIxeF
    vfVILkw6xL/jXJfdKTDc/w9zooYko/sKVUf3T8coNOadeYvMPvYpIvO3lSeBXoU4
    eEaUj13ZRyJFiLW2qtpNY1sVGgDrjYxMGMbrqhtc7BL1g3CsDQrKSUfCKScWLsYG
    cu5khqwTFiM1qZXcknugOroT5S2kVm2/H4JUP45wunQlWADBbGBh+wCTRKJsGnJk
    v4ihRGGdAgMBAAECggEAbNPmzQzJ2BwjkhmpK5BVsVihfvaq9nYQo3cyekoeT+vO
    xWTGIb8UDRFHfmfii6Mw2rSlP5dCZImqzHAXQjneo4MTupSc8GM3Huklw/xZeTrP
    n2iUkv+OsqLrB6g9Q3eV9zh/td0wzNuFP5MC+nAU/e5g76Py0xX12MMDzrQtDCLC
    /NmjLxy9TnRZtR7+SIroYc1Z7AZv0RBc9Rz8YwJL/8UByE8GLEmaWJFzNK3NQt/s
    1V7pRJY/C0S53/KJxOhPOJ4Wc8dZaSa6zBMPmiRg27+wXpY1OALc/DR5vmHTAyQi
    ZbPSbaVirKhRqVhusOr3r3PDrpigzBgpOId588lC0QKBgQDN9Gz3kN/C/d2gKCbJ
    vjNgzhvtvIoyAIs9BF0AuFabGSpz82WcayrnPtkMz7f9UFQLDfLM1Bdw+NoZq95W
    48S5F1emE0+XT9vmmA0hLR2PT+Yf7ULZWrVkYRe5St0bidvlwQG0k4yJuVmAu4ox
    EnBS+Khs7ySkeLlrQMaHwxq+lwKBgQDMGcUj3NrU7Q9Y4pzJabiYIht87nmq8E9e
    VOlPDfLwDJtQ9Niuhzdk1xHW2f5B1xMIRbGegamzUR4Jku/Yvg/zZNUchVjuDD7/
    2pJuS/fRND/m0IH3bnYD8btPIab1GcC6bqBcX0/6cv5q55xl5RpRq4w49USbf2KB
    X1SHuH6b6wKBgQDCPg8vhnGjxC7sSDIc/8gROxLYK4PjGOQ5jg3xCeqUqS2C4kIp
    PmHea0XmcVpEDSjWrDccu8PIBswcfh5asMLvFnbR6VCdkvIBD9MCQTyp119hKTJt
    MMH3hCMN3O+gc2rzzA7Bso9PrYIeicIR+iP5/Q9Mfld+z2WBJDyZ+ocUzQKBgHpE
    RdECESXVDYiV2I7gAnFAnW7t/XzlkOZVv55YINyk8LZCtzt2TTzfihRHawVOLlya
    Q5lM27hMM85Qc9ZHpY6NLQ105J1WQLdM3MOuRrrQric7aWAskA401ZzF8BqMXuRQ
    OUic4HCMStUIAq0X3fhm6A2HAJ6WZRBTZ3QWleIZAoGAdZbSYYPF74QKRuzyfq0f
    gf4kaOMDQh2p+N4/GaaB1Xp/geMrvt9/bsAQHsTDSpb/6Abh3cuAA1IebTDd4027
    Jem8nflEDp/1chJWdWVe2H+ArtFgXy9ZjdIUpM5fTFHDtqanpncOFOzLinx/1kTX
    IHnEwdqGgjPfSgdYaEYt5e8=
    -----END PRIVATE KEY-----
  postgres_ssl_ca: |
    -----BEGIN CERTIFICATE-----
    MIIDgzCCAmugAwIBAgIJAMIEExxt0wjsMA0GCSqGSIb3DQEBCwUAMFgxCzAJBgNV
    BAYTAlBMMRAwDgYDVQQIDAdXUk9DTEFXMRAwDgYDVQQHDAdXUk9DTEFXMSUwIwYD
    VQQKDBxFbGFzdGljc2VhcmNoU29mdHdhcmVGYWN0b3J5MB4XDTIxMDcxNjA4NTYz
    N1oXDTMxMDcxNDA4NTYzN1owWDELMAkGA1UEBhMCUEwxEDAOBgNVBAgMB1dST0NM
    QVcxEDAOBgNVBAcMB1dST0NMQVcxJTAjBgNVBAoMHEVsYXN0aWNzZWFyY2hTb2Z0
    d2FyZUZhY3RvcnkwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDKXjbt
    MTEV4IzZiFq1N+DKiSQDubW9MNGrzkgrBzrso1K3UwTImTsAgzUH/8WHyQPGQ1o7
    o3v8VjuPzhuxlkgZU6A2sOVpqorZSyWjWM24DsNfJg45l+PoAzaKOoV1WSmCfSoQ
    NkyCAR4h8jzgwZUPKEfr6fY6Rv2a2WK7muCggJfiWweec1aQg2R0lNiQ8DRhQDPg
    U7EJdLMz61HWI8/TFEQIVZKPtkUBRR5uovZ+pXjtkNR6yyIP0cvfhXO4n4S474wx
    OOg5DevdFcXvKSJ5rvti502fJuma38KllHEvaHFEurECke3bPna6KzoG9WzrULc4
    5hDSvWO8D4adNhMJAgMBAAGjUDBOMB0GA1UdDgQWBBTJFta/f7YOieENO/z/DmBX
    OwbwQDAfBgNVHSMEGDAWgBTJFta/f7YOieENO/z/DmBXOwbwQDAMBgNVHRMEBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQALr9HynXIiICt0JjHs5KmzYcz325QkDyHL
    OC/VVY2JHLzrH8JjRN/itF2V03Snj7NSieG1q/N/Z2gt/jVMyQE1R4bW4bmMnIZM
    9jtaUgi5y/HOPpIYMfIB0PyYUsPzJT0JECc6x+kXkrzr31TJod65IoPVSMi+b5Oy
    uXOh1BLG/+HyY39cMbDCznoY9t7AprGZcDfb+Psv/9wwFUnk4ke6uSqhDalTV/fA
    uTQ/QNO1330Wb8xq3xKgPXcndszEwD6OVvU4Dl6S4gIEeopFQHsJWBkVuFKs2rIw
    2C4WVzfxoWOSqH0SMxDQorFIWMgphb4cnhmS8OW7zDR7YuvMU6Yz
    -----END CERTIFICATE-----
