- block:
    - name: Class Remove Folders
      become_user: "{{ runtime_user }}"
      ignore_errors: true
      block:
        - name: Remove container Data Folders
          file:
            path: "{{ item }}"
            state: absent
          with_items:
            "{{ folder_list }}"
